---
hdp_major_version: "{{ hdp_version | regex_replace('.[0-9]+.[0-9]+[0-9_-]*$','') }}"

hdp_repo_url: "{{ hdp_base_url }}/HDP/centos{{ ansible_distribution_major_version }}/2.x/updates/{{ hdp_version }}"
hdp_repo_target: "api/v1/stacks/HDP/versions/{{ hdp_major_version }}/operating_systems/redhat{{ ansible_distribution_major_version }}/repositories/HDP-{{ hdp_major_version }}"

utils_repo_url: "{{ hdp_base_url }}/HDP-UTILS-{{ hdp_utils_version }}/repos/centos{{ ansible_distribution_major_version }}"
utils_repo_target: "api/v1/stacks/HDP/versions/{{ hdp_major_version }}/operating_systems/redhat{{ ansible_distribution_major_version }}/repositories/HDP-UTILS-{{ hdp_utils_version }}"
