---
packages:
  - python27-httplib2       # required for calling Ambari API from Ansible
  - openssh-clients         # scp required by Ambari
  - curl                    # curl required by Ambari
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  - ntp                     # ntp required by Hadoop

ntp_service_name: ntpd

epel_url: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"

ambari_repo_url: "http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/{{ ambari_version }}/ambari.repo"
ambari_repo_destination: "/etc/yum.repos.d/ambari.repo"
