---
- block:
    - name: Set correct permissions to the http secret key
      file:
        path: /etc/security/http_secret
        owner: hdfs
        group: hadoop
        mode: 0440
  when: hostvars[groups['ambari-server']|sort|list|first]['security'] != "none" and hostvars[groups['ambari-server']|sort|list|first]['security_options']['http_authentication']|default(false)
