---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: "Install the HDF Management Pack"
  shell: "echo yes | ambari-server install-mpack --mpack={{ main_repo_url }}/tars/hdf_ambari_mp/{{ mpack_filename }} --purge"
  when: product.name == "hdf"
  notify: Restart ambari-server
  args:
    creates: "/var/lib/ambari-server/resources/mpacks/{{ mpack_filename | regex_replace('.tar.gz$','') }}"

- meta: flush_handlers

- name: "Modify the {{ product.name|upper }} base_url repository for {{ product.name|upper }} {{ minor_version }}"
  uri:
    url: http://{{ ansible_nodename }}:8080/{{ main_repo_target }}
    method: PUT
    force_basic_auth: yes
    user: "{{ ambari_admin_user }}"
    password: "{{ ambari_admin_password }}"
    headers: '{"X-Requested-By":"ambari"}'
    body: " {\"Repositories\" : { \"base_url\" : \"{{ main_repo_url }}\", \"verify_base_url\": true } }"
    body_format: raw
    status_code: 200,201,202
    return_content: no

- name: "Modify the HDP-UTILS base_url repository for {{ product.name|upper }} {{ minor_version }}"
  uri:
    url: http://{{ ansible_nodename }}:8080/{{ utils_repo_target }}
    method: PUT
    force_basic_auth: yes
    user: "{{ ambari_admin_user }}"
    password: "{{ ambari_admin_password }}"
    headers: '{"X-Requested-By":"ambari"}'
    body: " {\"Repositories\" : { \"base_url\" : \"{{ utils_repo_url }}\", \"verify_base_url\": true } }"
    body_format: raw
    status_code: 200,201,202
    return_content: no
