---
- name: Create Ansible groups
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add the nodes to hadoop-cluster and role specific groups
      include: "add_nodes_{{ cloud_name }}.yml"
      when: item.count > 0
      with_items: "{{ nodes }}"

- name: Gather facts from all nodes
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes

- name: Apply the ambari-blueprint role to the ambari-server group
  hosts: ambari-server
  any_errors_fatal: true
  become: yes
  roles:
    - ambari-blueprint
