---
- set_fact: outer_loop="{{ item }}"

- name: Create {{ outer_loop.group }} nodes
  os_server:
    name: "{{ outer_loop.group }}{{ (outer_loop.count > 1) | ternary(local_loop,'') }}{{ cloud_config.name_suffix|default('') }}"
    image: "{{ outer_loop.image }}"
    flavor: "{{ outer_loop.flavor }}"
    key_name: "{{ cloud_config.ssh.keyname }}"
    availability_zone: "{{ cloud_config.zone }}"
    state: present
    wait: true
    timeout: 900
    validate_certs: false
    meta:
      group: "{{ outer_loop.group }}"
  loop_control:
    loop_var: local_loop
  with_sequence: count="{{ outer_loop.count }}" format=-%02x
