---
- name: Create Ansible groups
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add the nodes to hadoop-cluster and role specific groups
      include: "{{ add_nodes_playbook }}"
      when: item.count > 0
      with_items: "{{ nodes }}"

- name: Apply the ambari-agent role to the hadoop-cluster group
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  roles:
    - ambari-agent

- name: Apply the ambari-server role to the ambari-server group
  hosts: ambari-server
  any_errors_fatal: true
  become: yes
  roles:
    - ambari-server
