---
- name: Create Ansible groups
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add the nodes to hadoop-cluster and role specific groups
      include: add_nodes_openstack.yml
      when: item.count > 0
      with_items: "{{ nodes }}"

- name: Apply the common role to the hadoop-cluster group
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  roles:
    - common
