---
- name: Install the ambari-server package (yum)
  yum:
    name: ambari-server
    update_cache: yes
    state: latest
  notify: Reload systemd
  when: ansible_os_family|lower == "redhat"

- name: Install the ambari-server package (apt)
  apt:
    name: ambari-server
    update_cache: yes
    state: latest
  when: ansible_os_family|lower == "debian"

- name: Fix Ambari 2.4 bug in RHEL/CentOS 7
  lineinfile:
    dest: /etc/rc.d/init.d/ambari-server
    state: present
    insertafter: '^export ROOT=`dirname.*$'
    line: 'export ROOT="/"'
  when: ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int == 7

- meta: flush_handlers

- name: Run Ambari Server setup
  shell: /usr/sbin/ambari-server setup -s
  notify: Restart ambari-server

- meta: flush_handlers

- name: Make sure all of the Ambari Agents have registered
  uri:
    url: http://{{ ansible_nodename }}:8080/api/v1/hosts/{{ hostvars[item]['ansible_nodename']|lower }}
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin
    headers: '{"X-Requested-By":"ambari"}'
    status_code: 200,201,202,404
    return_content: no
  with_items: "{{ groups['hadoop-cluster'] }}"
  register: result
  until: "result.status != 404"
  retries: 100
  delay: 5
